bind + split-window -h # horizontal split
bind _ split-window -v # vertical split

## select pane
unbind Up
unbind Down
unbind Left
unbind Right
bind j select-pane -D
bind k select-pane -U
bind h select-pane -L
bind l select-pane -R

# resize pane
unbind C-Up
unbind C-Down
unbind C-Left
unbind C-Right
bind -r J resize-pane -D
bind -r K resize-pane -U
bind -r H resize-pane -L
bind -r L resize-pane -R
