vim.keymap.set('n', '<leader>cb', function()
    vim.cmd.vsplit()
    vim.cmd.term('go build')
end)
vim.keymap.set('n', '<leader>cr', function()
    vim.cmd.vsplit()
    vim.cmd.term('go run main.go')
end)
vim.keymap.set('n', '<leader>ct', function()
    vim.cmd.vsplit()
    vim.cmd.lcd('%:p:h')
    vim.cmd.term('go test')
end)
vim.keymap.set('n', '<leader>cs', function()
    local filepath = vim.api.nvim_buf_get_name(0)
    local test_filepath = filepath:gsub("%.go$", "_test.go")
    vim.cmd.vsplit(test_filepath)
end)
